### ISSUE TITLE
mkdocs-material blog broken in v2.9.3

### ISSUE THREAD

**Issue by eloo-abi** [lukasgeiter/mkdocs-awesome-nav#111]
Hi,

we have recently rolled out the latest update and i have seen that now mkdocs-material blog is not working properly anymore. 

With v2.9.3 of awesome pages the navigation is gone for the blog posts..

so it looks now like this:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/3c2f8b59-d45a-46a0-922e-301398cd31d3">

with v2.9.2 it looks like this (which is the expected):
<img width="299" alt="image" src="https://github.com/user-attachments/assets/b6548e53-588f-457f-895b-d0f82d84a3f6">

My config looks mostly like this:

```
plugins:
  - awesome-pages
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      categories_toc: true

nav:
  - Blog: 
    - blog/index.md
```
and i don't use any `.pages` right now

**Comment by lukasgeiter** [comment]
I wasn't able to reproduce your issue. Which version of mkdocs and mkdocs-material are you using?

**Comment by eloo-abi** [comment]
Hi, 

i have the following versions running:

```
mkdocs==1.6.1
mkdocs-material==9.5.47
markupsafe==3.0.2
mkdocs-git-revision-date-localized-plugin==1.3.0
mkdocs-awesome-pages-plugin==2.9.2  # 2.9.3 has a bug https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/111
mkdocs-glightbox
```

not sure if this is related but i'm using tabs navigation as well

```
theme:
  features:
    - navigation.tabs
 ```

**Comment by lukasgeiter** [comment]
Hmm I have the same versions and also tried with the tabs feature. Could you provide me with a reproducable example?

**Comment by eloo-abi** [comment]
@lukasgeiter for sure..

i also got a second conditions which needs to be set that the bug is visible..

its the `...` in the "bug-cause" navigation

so a "broken" example looks like this

```
site_name: Github #111

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - awesome-pages
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      categories_toc: true

nav:
  - Bug-cause:
      - ... | flat | conventions/*.md
  - Blog: 
      - blog/index.md
```

maybe this helps to find the bug..
