### ISSUE TITLE
Add file in a subfolder to the nav

### ISSUE THREAD

**Issue by timmeinerzhagen** [lukasgeiter/mkdocs-awesome-nav#115]
From a ` .pages` config you can only refer to a file in the same folder explicitly - which is a different behaviour from the normal mkdocs nav. If you do refer to a file in another folder, then the navigation entries compile with urls to the static `.md` files, leading to 404 errors (see entires SubIndex/Test1 below).

Example configuration with according results:
```yml
nav:
- Overview:   'index.md'      # Works
- Page:       'page.md'       # Works
- SubIndex:   'test/index.md' # 404 - Links to test/index.md
- Test1:      'test/test.md'  # 404 - Links to test/test.md
- Test2:      'test/test/'    # Works (but does no validation)
- Thing:      'thing/test/'   # Works (but does no validation)
- test                        # Works
```

This was brought up in https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/108#issuecomment-2407376494 and marked as resolved since you can link with i.e. `test/test/`  instead of `test/test.md`. 
However, this also removes the validation, which checks that all nav entries actually exist - which I do still need to ensure Integrity. 

Is this intended behaviour?
