### ISSUE TITLE
i18n nav_translations are ignored by sort settings

### ISSUE THREAD

**Issue by mschrumpf** [lukasgeiter/mkdocs-awesome-nav#120]
Hi, 
I encountered an issue when using both mkdocs-awesome-nav and mkdocs-static-i18n. 
Sorting ignores directories translated with the i18n plugin. 

Relevant bits of `mkdocs.yml`: 

```
plugins:
  - awesome-nav
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: de
          nav_translations:
            Payment: Zahlung 
```

Relevant bits of `docs/.nav.yml`: 

```
sort: 
  by: title
  sections: mixed
  ignore_case: true
  type: natural
```

The issue surfaces in the directory `docs/guides/payment/`. When viewing the German translation of the docs, this section is translated to "Zahlung", as it should be. However, it is still sorted in the middle of the list, as if it were spelled "Payment". 

![Image](https://github.com/user-attachments/assets/dc062ac5-383f-4118-bdd3-8128ab571636)

I have tried specifying a title in the metadata of `docs/guides/payment/index.md` or `index.de.md` to no avail. The only workaround seems to be using different folders for each language. That just isn't doable because we want to use the English pages as a fallback for missing German translations.
