### ISSUE TITLE
Having trouble using multiple .pages files in different directories

### ISSUE THREAD

**Issue by jeffjg** [lukasgeiter/mkdocs-awesome-nav#71]
Hello!

I'm having trouble with using multiple `.pages` files in multiple directories. I have one `.pages` file in the root directory that's intended to be used for the main navigation, and then another `.pages` file in a directory called `design` that's intended to be used for the navigation of the pages within the design section.

Here's the folder directory:

```
/docs
  .pages
  /design
    .pages
```

And here's what the .pages files look like. This is the first one, in the root `/docs` directory:

```
nav:
    - Curriculum: curriculum
    - Design: design
    - Items: items
    - Quality Control: qc
```

And here's the content in the .pages file within the `design` directory:

```
nav:
    - Introduction: general
    - Book Design: book_design
    - Figure Design: figure_design
```

The issue is when I click on the Design link in the top nav on my website, it goes to the `design/general` location. What I'm hoping to have it do is instead go to the `design/index.md` file, and then once the `Introduction` link in Design is clicked, then it goes to the `design/general` location.

Does anyone have any idea how I can it to function like this?

Thank you!!!

**Comment by kamilkrzyskow** [comment]
Hi, in your `design` `.pages` file try:
```yml
nav:
    - index.md
    - Introduction: general
    - Book Design: book_design
    - Figure Design: figure_design
```
or
```yml
nav:
    - ...
    - Introduction: general
    - Book Design: book_design
    - Figure Design: figure_design
```
or if you're using the `i18n` plugin:
```yml
nav:
    - ... | index*.md
    - Introduction: general
    - Book Design: book_design
    - Figure Design: figure_design
```

I'm using the `material` theme with `index pages` and `navigation tabs` features on, together with the `i18n` plugin:
For the top level (root -> tab) I have to use the third method in the `tab` directories to directly set `index` at the top.
Apart of that in deeper directories I just use `...` in the nav and it does include the index at the top. 

It breaks at the navigation tab level since it's a feature of the material theme that could get the link before the `...` is processed by the plugin 🤔, but I never investigated it 🤷.
